name: Compressors
main: io.github.levtey.Compressors.Compressors
version: 0.0.1
author: levtey
api-version: 1.15
commands:
  compressors:
    description: Main plugin command
    usage: /<command> help
permissions:
  compressors.place:
    description: Allows you to place a compressor
    default: true
  compressors.give:
    description: Allows you to give someone a compressor
    default: op
  compressors.reload:
    description: Allows you to reload the configs
    default: op
  compressors.create:
    description: Creates an item stack in the config you can copy and put in the recipes
    default: op